id: netlify-api-key

info:
  name: Netlify API Key
  author: YoruYagami
  severity: high

file:
  - extensions:
      - all

    extractors:
      - type: regex
        regex:
          - "netlify_[a-zA-Z0-9]{40}"
