name: Nuclei-Templates-Collecter

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Specify the version of Go you want to use

    - name: Installing unzip and cent via binary
      run: |
        sudo apt install unzip
        wget https://github.com/xm1k3/cent/releases/download/v1.3.4/cent_1.3.4_linux_amd64.zip
        unzip cent_1.3.4_linux_amd64.zip -d cent_1.3.4_linux_amd64
        mv cent_1.3.4_linux_amd64/cent /usr/local/bin/cent
        rm -rf cent_1.3.4_linux_amd64.zip cent_1.3.4_linux_amd64

    - name: Running cent
      run: |
        cent --config .cent.yaml -p cent-nuclei-templates

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        
        # Check if there are changes before committing
        if ! git diff --cached --exit-code; then
          IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
          git commit -m "Updated List: $IST_DATE"
          git push
        else
          echo "No changes to commit"
        fi
